AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Okapi JSON Web API

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/lambda/release/lambda.zip
      Handler: DUMMY
      Runtime: provided
      MemorySize: 128
      Events:
        Web:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        WebRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
